# Docker compose file that sets up environment:
version: "3.9"

services:
  hunter-labs:
    image: hunteri/py-ops:0.1
    container_name: hunter-labs
    tty: true
    stdin_open: true
    volumes:
      - ../.aws:/root/.aws
      - ../.ssh:/root/.ssh
      - ./tools:/tools
      - ./utils:/utils
