---

#- name: Pause for 30 seconds to allow AWS instance to initialise
#  pause:
#    seconds: 30

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install useful packages
  apt:
    pkg:
    - unzip

- name: Install AWS EFS Mount helper
  include: "efs_mount_helper.yml"
