---
# Playbook deletes specified users to ensure they cannot log in again

- name: Generate config
  hosts: localhost
  become: yes
  vars_prompt:

  - name: aws_environment
      prompt: What environment are you configuring MUST be one on dev|test|prod
      private: no

    - name: aws_profile
      prompt: What is the name of the aws_profile for the environment
      private: no

    - name: aws_region
      prompt: What is the name of the AWS Region infrastructure will be build it, eg us-east-1
      private: no

    - name: org_name
      prompt: What is the name of the Organisation config is being built for (eg hunter-labs)
      private: no

  roles:
    - gen_config
