- name: Debug
  ansible.builtin.debug:
    msg:
      - 'aws_environment: {{ aws_environment }}'
      - 'aws_profile: {{ aws_profile }}'
      - 'aws_region: {{ aws_region }}'
      - 'org_name: {{ org_name }}'

- name: Remove any existing config files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tools/ansible/config/init_ansible_{{ aws_environment }}.sh
    - /tools/packer/config/pkr_vars_{{ aws_environment }}.sh


- name: Generating ansible config
  ansible.builtin.template:
    src: init_ansible_config.j2
    dest: /tools/ansible/config/init_ansible_{{ aws_environment }}.sh
    owner: root
    group: root
    mode: 0555
    unsafe_writes: yes

- name: Generating packer config
  ansible.builtin.template:
    src: init_packer_config.j2
    dest: /tools/packer/config/pkr_vars_{{ aws_environment }}.sh
    owner: root
    group: root
    mode: 0555

